# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f49d8556-ac03-4140-a879-5af144d7e81d";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/775E-7F47";
    fsType = "vfat";
  };


  fileSystems."/data/music" = {
    device = "data/music";
    fsType = "zfs";
  };

  fileSystems."/data/games" = {
    device = "data/games";
    fsType = "zfs";
  };

  fileSystems."/data/backup" = {
    device = "data/backup";
    fsType = "zfs";
  };

  fileSystems."/data/photos" = {
    device = "data/photos";
    fsType = "zfs";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/b2aa2e02-cd4c-40b6-a84c-5e06a19971b2"; }];

}
