# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f49d8556-ac03-4140-a879-5af144d7e81d";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/775E-7F47";
    fsType = "vfat";
  };

  fileSystems."/tank" = {
    device = "tank";
    fsType = "zfs";
  };

  fileSystems."/tank/backup" = {
    device = "tank/backup";
    fsType = "zfs";
  };

  fileSystems."/tank/media" = {
    device = "tank/media";
    fsType = "zfs";
  };

  fileSystems."/tank/games" = {
    device = "tank/games";
    fsType = "zfs";
  };

  fileSystems."/tank/backup/yasnix" = {
    device = "tank/backup/yasnix";
    fsType = "zfs";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/ce9405eb-d20b-430f-80dd-adcda01bc5b7"; }];

}
