#!/usr/bin/env bash

# add workspaces
while read -r k v; do workspaces[$k]="$v"; done < <(hyprctl -j workspaces | gojq -r '.[]|"\(.id) \(.monitor)"')

# check occupied workspaces
for num in "${!workspaces[@]}"; do
  o[$num]=1
done
# generate initial widget
generate

active_workspace() {
  hyprctl activewindow | rg workspace | sed 's/\s*workspace: \([0-9]\+\).*/\1/g'
}

# main loop
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | rg --line-buffered "workspace|mon(itor)?" | while read -r line; do
done
